name: Deploy to Contabo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Get your latest repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Connect to Contabo and deploy
      - name: Deploy to Contabo
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          key: ${{ secrets.CONTABO_SSH_KEY }}
          port: 22

          script: |
            cd /home/door2dev/AFTER9

            git pull origin main

            # Add your deployment commands below
            npm install
            npm run build
            pm2 restart 

            pm2 restart all
